tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "openssl"
brew "openssl@1.1" # wget dependency

brew "awscli"
brew "ack"
brew "anomalyco/tap/opencode"
brew "ariga/tap/atlas"
brew "bat"
brew "cloc"
brew "cmake"
brew "coreutils"
brew "diff-so-fancy"
brew "duckdb"
brew "gh"
brew "git"
brew "httpie"
brew "jsonnet"
brew "jq"
brew "less"
brew "librsvg"
brew "mise"
brew "pulumi/tap/pulumi"
brew "python3"
brew "rbenv"
brew "ssh-copy-id"
brew "tldr"
brew "tree"
brew "wget"
brew "zsh"

cask "iterm2"
cask "lm-studio"
cask "google-cloud-sdk"
cask "rancher"
cask "sf-symbols"
cask "visual-studio-code"
cask "raycast"
cask "notunes"
